In [10]:
import numpy as np

In [11]:
arr1 = np.arange(10).reshape(2,5)
print(arr1)
# >= <= != > < == 等关系运算符
# 还可以多个条件进行比较 与 & 或 ｜ 非 ～ Numpy里面这样使用 
# 但Python里面使用 and or not
arr2 = arr1>=4
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[False False False False  True]
 [ True  True  True  True  True]]


In [ ]:
# 同维数组比较 
arr3 = np.flipud(arr1)
print(arr3)
arr4 = arr1>=arr3
print(arr4)

[[5 6 7 8 9]
 [0 1 2 3 4]]
[[False False False False False]
 [ True  True  True  True  True]]
6
