In [ ]:
# 个人认为哈 这个找满足条件的值的所在位置就是找到索引，和切片，索引部分是密切相关的
# 使用where()函数
import numpy as np

In [2]:
# 创建一个矩阵
arr1 = np.arange(20).reshape(4,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
arr2 = np.where(arr1>=4)
print(arr2)
# 这个输出结果很诡异。两个结合一起看，比如: (0,4),(1,0) 给我一种花式索引的感觉
# 这个输出的结果可以直接作为花式索引使用
print(arr1[arr2])

(array([0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]), array([4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
