In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10).reshape(2,5)
print(arr1)
arr2 = np.fliplr(arr1)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[4 3 2 1 0]
 [9 8 7 6 5]]


In [ ]:
arr3 = arr1>=arr2
print(arr3)
# 掩码的作用之一主要是用来筛选出符合要求的值
print(arr1[arr3])
print(arr2[arr3])
# 使用掩码最后输出的结果是向量不是矩阵

[[False False  True  True  True]
 [False False  True  True  True]]
[2 3 4 7 8 9]
[2 1 0 7 6 5]
