In [18]:
import numpy as np

In [19]:
arr1 = np.arange(10).reshape(2,5)
print(arr1)
arr2 = np.fliplr(arr1)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[4 3 2 1 0]
 [9 8 7 6 5]]


In [20]:
# sum() 计算True个数
# any() 输出结果为True或者False 只要有True，结果就为True
# all() 全为True才返回True
arr3 = arr1>=arr2
print(arr3)
print(np.sum(arr3))
print(np.any(arr3))

[[False False  True  True  True]
 [False False  True  True  True]]
6
True
