In [1]:
import numpy as np

In [2]:
# 创建一个数组
arr1 = np.arange(10)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 视图（view）就是：创建了一个新的数组变量，但是它和原数组共享同一块内存数据。 没有创建新的变量
# 原数组改了，视图也会跟着被修改
cut1 = arr1[2:4]
print(cut1)
cut1[0] = 1000
print(cut1)
print(arr1) # 会发现原数组也跟着修改

[2 3]
[1000    3]
[   0    1 1000    3    4    5    6    7    8    9]


In [ ]:
# 创建一个矩阵
arr2 = np.arange(0,20).reshape(4,5)
print(arr2)
cut2 = arr2[0:2,0:2]
print(cut2)
cut2[0][0] = 100
print(cut2)
print(arr2) # 会发现原矩阵也会跟着改

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 1]
 [5 6]]
[[100   1]
 [  5   6]]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
