In [1]:
import numpy as np

In [8]:
# 创建一个向量
arr1 = np.arange(60,70)
print(arr1)
# 创建一个矩阵
arr2 = np.arange(10,19).reshape((3,3))
print(arr2)

[60 61 62 63 64 65 66 67 68 69]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [11]:
# 花式索引 输出结果仍然是一个向量
print(arr1[[0,3]])
# 矩阵的花式索引 我感觉就是方便找出一组数，比如对角线上的元素
print(arr2[[0,1],[0,1]]) # 0行1列 1行1列的元素

[60 63]
[10 14]
