In [1]:
import numpy as np

In [9]:
# 创建一个向量
arr1 = np.arange(40,50)
print(arr1)
# 创建一个矩阵
arr2 = np.arange(20,40).reshape(4,5)
print(arr2)

[40 41 42 43 44 45 46 47 48 49]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [8]:
# 向量的切片
print(arr1[1:4]) # 从第1个索引切到第4个索引之前
print(arr1[1:]) # 从第1个索引切到最后一个索引
print(arr1[:5]) # 从最开始的索引切到第5个索引之前
# 采样
print(arr1[::2]) # 每隔2个元素采样一次
print(arr1[1:-1:2]) # 从第1个索引开始切到倒数第1个索引之前，然后每隔2个元素采样一次

[41 42 43]
[41 42 43 44 45 46 47 48 49]
[40 41 42 43 44]
[40 42 44 46 48]
[41 43 45 47]


In [11]:
# 矩阵的切片
print(arr2[1:3,2:3]) # 切行索引1到行索引3之前，列索引2到列索引3之前
print(arr2[::2,::3]) # 行隔2个索引采样一次，列隔三个索引采样一次

[[27]
 [32]]
[[20 23]
 [30 33]]


In [14]:
# 行矩阵的提取
print(arr2[2,:]) #提取第2行，列都要
print(arr2[0:2,:]) #提取第0-1行，列都要

[30 31 32 33 34]
[[20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
# 列矩阵的提取
print(arr2[:,1]) # 会发现得到的不是矩阵，而是一个向量
print(arr2[:,1:3]) # 行都要，提取第1，2列

[21 26 31 36]
[[21 22]
 [26 27]
 [31 32]
 [36 37]]


In [ ]:
# 列矩阵单列提取得到矩阵
print(arr2[:,1].reshape(-1,1)) # （-1，1）中 -1为自动计算多少行，1表示1列。使用塑形函数变成矩阵
# 还有另外一个处理办法，就是先将向量变成矩阵，然后进行转置操作 .T ->这个操作仅针对矩阵，向量无法进行这个操作

[[21]
 [26]
 [31]
 [36]]
