In [7]:
import numpy as np

In [ ]:
# 创建向量
arr1 = np.array((1,2,3))
print(arr1)
# 访问向量中元素
print(arr1[1])  # 注意顺数第几个都是从0开始
print(arr1[-1]) # 倒数第一个

[1 2 3]
2
3


In [12]:
# 创建矩阵
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
# 访问矩阵中的元素
print(arr2[1,2])
# 修改矩阵中元素
arr2[1,2] = 8
print(arr2)

[[1 2 3]
 [4 5 6]]
6
[[1 2 3]
 [4 5 8]]
