In [17]:
import numpy as np

In [18]:
# 创建向量
arr1 = np.arange(10)
print(arr1)
arr2 = np.arange(10,20)
print(arr2)
# 创建矩阵
arr3 = np.arange(20).reshape(4,-1) 
print(arr3)
arr4 = np.arange(20,40).reshape(4,-1)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [ ]:
# 向量的拼接
arr5 = np.concatenate([arr1,arr2])
print(arr5)
# 矩阵的拼接
arr6 = np.concatenate([arr3,arr4]) # 本处省去axis = 0，默认 axis = 0 就是按行拼接 
print(arr6)
arr7 = np.concatenate([arr3,arr4],axis = 1) # axis = 1 是按列拼接
print(arr7)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[ 0  1  2  3  4 20 21 22 23 24]
 [ 5  6  7  8  9 25 26 27 28 29]
 [10 11 12 13 14 30 31 32 33 34]
 [15 16 17 18 19 35 36 37 38 39]]


In [31]:
# 向量分裂
arr8,arr9,arr10 = np.split(arr1,[2,8]) # 索引2，8位置截断
print(arr8,arr9,arr10)

[0 1] [2 3 4 5 6 7] [8 9]


In [33]:
# 矩阵分裂
arr11,arr12,arr13 = np.split(arr6,[2,5]) # 默认axis=0 按行分裂
print(arr11,'\n\n',arr12,'\n\n',arr13)
arr14,arr15,arr16 = np.split(arr3,[2,4],axis = 1) # 按列分裂
print(arr14,'\n\n',arr15,'\n\n',arr16,'\n\n')

[[0 1 2 3 4]
 [5 6 7 8 9]] 

 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]] 

 [[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]] 

 [[ 4]
 [ 9]
 [14]
 [19]] 


