In [1]:
import numpy as np

In [ ]:
# 创建向量
arr1 = np.arange(10)
print(arr1)
# 创建矩阵
arr2 = np.arange(20).reshape(4,-1) #reshape就是重塑
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# 向量不可直接进行转置，需要先变成矩阵才可进行。如果想直接变成列矩阵可以直接写reshape(-1,1)
arr3 = arr1.reshape(1,-1) # 升级成矩阵
print(arr3)
arr4 = arr3.T # 进行转置
print(arr4)

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [8]:
# 翻转有两个函数 左右翻转：fliplr() 上下翻转：flipud() 向量只可用上下翻转
arr1_ud = np.flipud(arr1)
print(arr1_ud)

arr2_ud = np.flipud(arr2)
arr2_lr = np.fliplr(arr2)
print(arr2_ud)
print(arr2_lr)


[9 8 7 6 5 4 3 2 1 0]
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
