In [2]:
import numpy as np

In [3]:
# 绝对值 abs()
arr1 = np.arange(-1,1)
print(arr1)
arr2 = np.abs(arr1)
print(arr2)

[-1  0]
[1 0]


In [4]:
# 三角函数 sin(x) cos(x) tan(x)
# 对数函数 lnx -> log(x) log2x -> log(x)/log(2) 换底公式的使用
# 指数函数 exp(x) 幂函数 某个数的x次方 num**x 


$\log_a b = \frac{\log_c b}{\log_c a}$

In [ ]:
# 聚合函数
arr3 = np.arange(10).reshape(2,5)
print(arr3)
print(arr3.shape)

# 主要有求和，求积，求最大最小，求平均，求标准差，求方差 sum() prod() max() min() mean() std() var()
# 大型数组可能出现缺失值，在函数名前加nan，来忽略缺失值 如：nansum()

print(np.sum(arr3,axis = 0)) # 列不动，逐行求和
print(np.sum(arr3,axis = 1)) # 行不动，逐列求和
print(np.sum(arr3)) # 整体求和

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[ 5  7  9 11 13]
[10 35]
45
