In [1]:
import numpy as np

In [ ]:
# dot（）函数 向量和矩阵相乘，只要混有向量，那么最终的结果一定是向量。相乘时遵循线性代数矩阵乘法规则。 向量和向量相乘的到的是标量
arr1 = np.arange(10).reshape(2,5)
print(arr1)
arr2 = np.arange(5)
print(arr2)
print(arr1.shape,arr2.shape) # 运算前可以先查看形状，确定是否能够运算
arr3 = np.dot(arr1,arr2)
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
(2, 5) (5,)
[30 80]
