In [1]:
import numpy as np

In [ ]:
# 同0数组
arr1 = np.zeros((8,8)) # 8行8列
print(arr1)
arr2 = np.zeros(8) # 默认1行8列
print(arr2)

In [10]:
# 同1数组
arr3 = np.ones((1,4))
print(arr3)

[[1. 1. 1. 1.]]


In [11]:
# 同某个数数组
arr4 = 8*np.ones((8,8))
print(arr4)

[[8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]]
