In [1]:
import numpy as np

In [2]:
# 创建一维数组
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
# 创建行矩阵
arr2 = np.array([[1,2,3]])
print(arr2)

[[1 2 3]]


In [4]:
# 创建列矩阵
arr3 = np.array([[1],[2],[3]])
print(arr3)

[[1]
 [2]
 [3]]


In [5]:
# 创建矩阵
arr4 = np.array([[1,2,3],[4,5,6]])
print(arr4)

[[1 2 3]
 [4 5 6]]
