In [8]:
import numpy as np 

In [9]:
# 创建数组从1开始 10之前结束
arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [10]:
# 创建数组 从0开始往后几个数
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# 创建数组 固定步长
arr3 = np.arange(1,10,2)
print(arr3)

[1 3 5 7 9]
