In [1]:
import numpy as np

In [ ]:
# 创建向量
arr1 = np.arange(10,20)
print(arr1)
# 创建矩阵
arr2 = np.arange(20,40).reshape(-1,10)
print(arr2)

[10 11 12 13 14 15 16 17 18 19]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [ ]:
# 进行加减运算 
# 向量和矩阵进行运算，向量自动升级成矩阵
# 在不适配另外一个矩阵的时候，该矩阵会被广播，来适配另外一个矩阵的形状。但是有时候完全适配不了
print(arr1+arr2)

[[30 32 34 36 38 40 42 44 46 48]
 [40 42 44 46 48 50 52 54 56 58]]
